[package]
name = "rpub"
version = "0.1.0"
edition = "2021"


[dependencies]
argh = "0.1.12"
zip = "2.2.0"
termion = "4.0.2"
lazy_static = "1.5.0"

[profile.release]
strip = true
opt-level = "z"
lto = true